openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:9080
  description: Generated server url
paths:
  "/rest/vt/manager/{id}":
    get:
      tags:
      - employee-rest-controller
      operationId: getEmployeesByThread
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"
  "/rest/employee":
    get:
      tags:
      - employee-rest-controller
      operationId: getAllEmployees
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"
  "/rest/byManager/{id}":
    get:
      tags:
      - employee-rest-controller
      operationId: getEmployeesByManagerID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/EmployeeDTO"
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        description:
          type: string
        jobLevel:
          type: integer
          format: int32
        createdDate:
          type: string
          format: date
        lastUpdated:
          type: string
          format: date-time
    EmployeeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        jobTitle:
          type: string
        department:
          type: string
        managerName:
          type: string
        hireDate:
          type: string
